python  trainer.py \
        --dataset cifar100 \
        --num-classes 100 \
        --data_augmentation \
        --model densenet \
        --depth 100 \
        --growthRate 12 \
        --epochs 300 \
        --schedule 150 225 \
        --gamma 0.1 \
        --wd 1e-4 \
        --train-batch 64 \
        --learning_rate1 0.1 \
        --learning_rate2 0.001 \
        --embedding-model vgg16 \
        --checkpoint checkpoints/cifar100/leapdensenet-bc-100-12-vgg16-lr01-b128-dataaug-magnetloss-iclr \
        --leap \
        --plot
