python  trainer.py \
        -a densenet \
        --dataset cifar100 \
        --depth 100 \
        --growthRate 12 \
        --train-batch 64 \
        --epochs 300 \
        --schedule 150 225 \
        --wd 1e-4 \
        --gamma 0.1 \
        --checkpoint checkpoints/cifar100/1-densenet-bc-100-12 \
        --num-classes 100 \
        --learning_rate1 0.1 \
        --data_augmentation \
        --random
